version: '2'
services:
  db:
    restart: unless-stopped
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
    - ${VOLUME_BASE}/mysql:/var/lib/mysql

  web:
    restart: unless-stopped
    image: tsn-ranksystem:1.3.7
    depends_on:
    - db
    ports:
    - "8081:80"
    volumes:
    - ${VOLUME_BASE}/tsn/config:/app/other
    - ${VOLUME_BASE}/tsn/logs:/app/logs

  ts3:
    restart: unless-stopped
    image: teamspeak
    environment:
      TS3SERVER_LICENSE: accept
    ports:
    - 9987:9987/udp
    - 10011:10011
    - 30033:30033
    volumes:
    - ${VOLUME_BASE}/ts3:/var/ts3server/

